### ISSUE TITLE
Missing information on vrpn installation and setup

### ISSUE THREAD

**Issue by fervanegas** [qutas/info#2]
We will need to add information on installation and setup of vrpn to use the vicon at DVP

**Comment by pryre** [comment]
I've added this as a package pre-req, and have added proper rosdep instructions to the Downloading & Updating the Workspace" o the "The QUTAS Flight Stack" in the guides. This should make things a lot simpler all around.

Could you please check if this installs the vrpn_client_ros package as expected?
